<?php

declare(strict_types=1);

namespace NeoPHP\Package\Orm\Platform;

use NeoPHP\Component\Database\Contract\ConnectionInterface;
use NeoPHP\Package\Orm\Contract\AbstractPlatform;
use NeoPHP\Package\Orm\Schema\Column;
use NeoPHP\Package\Orm\Schema\ForeignKey;
use NeoPHP\Package\Orm\Schema\Index;
use NeoPHP\Package\Orm\Schema\Schema;
use NeoPHP\Package\Orm\Schema\Table;

class PgsqlPlatform extends AbstractPlatform
{
    public const ACTIONS = ['a' => null, 'r' => null, 'c' => 'CASCADE', 'n' => 'SET NULL', 'd' => 'SET DEFAULT'];

    public function getName(): string
    {
        return 'pgsql';
    }

    public function getColumnDeclaration(Column $column, bool $inlinePrimaryKey = false): string
    {
        return $this->getTypeDeclaration($column)
            . ($column->autoincrement ? ' GENERATED BY DEFAULT AS IDENTITY' : '')
            . $this->getDefaultDeclaration($column)
            . ($column->nullable ? ($column->default === null && !$column->autoincrement ? ' DEFAULT NULL' : '') : ' NOT NULL');
    }

    public function getTypeDeclaration(Column $column): string
    {
        return match ($column->type) {
            'string' => 'VARCHAR(' . ($column->length ?? 255) . ')',
            'text' => 'TEXT',
            'integer' => 'INT',
            'smallint' => 'SMALLINT',
            'bigint' => 'BIGINT',
            'float' => 'DOUBLE PRECISION',
            'decimal' => 'NUMERIC(' . ($column->precision ?? 10) . ', ' . ($column->scale ?? 0) . ')',
            'boolean' => 'BOOLEAN',
            'datetime' => 'TIMESTAMP(0) WITHOUT TIME ZONE',
            'date' => 'DATE',
            'time' => 'TIME(0) WITHOUT TIME ZONE',
            'json' => 'JSON',
            'guid' => 'UUID',
            default => strtoupper($column->type),
        };
    }

    public function introspect(ConnectionInterface $connection): Schema
    {
        $schema = new Schema();
        $tables = $connection->fetchFirstColumn("SELECT table_name FROM information_schema.tables WHERE table_schema = current_schema() AND table_type = 'BASE TABLE' ORDER BY table_name");

        foreach ($tables as $name) {
            $table = new Table((string) $name);

            foreach ($connection->fetchAllAssociative('SELECT column_name, data_type, character_maximum_length, numeric_precision, numeric_scale, is_nullable, column_default, is_identity FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = ? ORDER BY ordinal_position', [$name]) as $row) {
                $dataType = strtolower((string) $row['data_type']);
                $length = $row['character_maximum_length'] !== null ? (int) $row['character_maximum_length'] : null;
                $default = $row['column_default'] === null ? null : (string) $row['column_default'];
                $autoincrement = $row['is_identity'] === 'YES' || ($default !== null && str_starts_with($default, 'nextval('));
                $type = match (true) {
                    $dataType === 'character varying' => 'string',
                    $dataType === 'character' => $length === 36 ? 'guid' : 'string',
                    $dataType === 'text' => 'text',
                    $dataType === 'integer' => 'integer',
                    $dataType === 'smallint' => 'smallint',
                    $dataType === 'bigint' => 'bigint',
                    $dataType === 'boolean' => 'boolean',
                    in_array($dataType, ['double precision', 'real'], true) => 'float',
                    $dataType === 'numeric' => 'decimal',
                    str_starts_with($dataType, 'timestamp') => 'datetime',
                    $dataType === 'date' => 'date',
                    str_starts_with($dataType, 'time') => 'time',
                    in_array($dataType, ['json', 'jsonb'], true) => 'json',
                    $dataType === 'uuid' => 'guid',
                    default => $dataType,
                };

                $table->addColumn(new Column(
                    (string) $row['column_name'],
                    $type,
                    $type === 'string' ? $length : null,
                    $row['is_nullable'] === 'YES',
                    $autoincrement ? null : $this->normalizeDefault($default),
                    $autoincrement,
                    $type === 'decimal' ? (int) $row['numeric_precision'] : null,
                    $type === 'decimal' ? (int) $row['numeric_scale'] : null,
                ));
            }

            $indexes = [];
            $sql = 'SELECT i.relname AS name, ix.indisunique AS is_unique, ix.indisprimary AS is_primary, a.attname AS column_name, array_position(ix.indkey::int2[], a.attnum) AS position'
                . ' FROM pg_class t INNER JOIN pg_index ix ON t.oid = ix.indrelid INNER JOIN pg_class i ON i.oid = ix.indexrelid'
                . ' INNER JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(ix.indkey) INNER JOIN pg_namespace n ON n.oid = t.relnamespace'
                . ' WHERE t.relname = ? AND n.nspname = current_schema() ORDER BY i.relname, position';

            foreach ($connection->fetchAllAssociative($sql, [$name]) as $row) {
                $indexes[(string) $row['name']]['columns'][] = (string) $row['column_name'];
                $indexes[(string) $row['name']]['unique'] = (bool) $row['is_unique'];
                $indexes[(string) $row['name']]['primary'] = (bool) $row['is_primary'];
            }

            foreach ($indexes as $indexName => $index) {
                if ($index['primary']) {
                    $table->setPrimaryKey($index['columns']);
                    continue;
                }

                $table->indexes[$indexName] = new Index($indexName, $index['columns'], $index['unique']);
            }

            $keys = [];
            $sql = 'SELECT con.conname AS name, att.attname AS column_name, cl2.relname AS foreign_table, att2.attname AS foreign_column, con.confdeltype AS on_delete'
                . ' FROM pg_constraint con INNER JOIN pg_class cl ON cl.oid = con.conrelid INNER JOIN pg_namespace n ON n.oid = cl.relnamespace'
                . ' INNER JOIN pg_class cl2 ON cl2.oid = con.confrelid'
                . ' CROSS JOIN LATERAL unnest(con.conkey, con.confkey) WITH ORDINALITY AS u(local_column, remote_column, position)'
                . ' INNER JOIN pg_attribute att ON att.attrelid = con.conrelid AND att.attnum = u.local_column'
                . ' INNER JOIN pg_attribute att2 ON att2.attrelid = con.confrelid AND att2.attnum = u.remote_column'
                . " WHERE con.contype = 'f' AND cl.relname = ? AND n.nspname = current_schema() ORDER BY con.conname, u.position";

            foreach ($connection->fetchAllAssociative($sql, [$name]) as $row) {
                $keyName = (string) $row['name'];
                $keys[$keyName]['columns'][] = (string) $row['column_name'];
                $keys[$keyName]['foreignColumns'][] = (string) $row['foreign_column'];
                $keys[$keyName]['foreignTable'] = (string) $row['foreign_table'];
                $keys[$keyName]['onDelete'] = self::ACTIONS[(string) $row['on_delete']] ?? null;
            }

            foreach ($keys as $keyName => $key) {
                $table->foreignKeys[$keyName] = new ForeignKey($keyName, $key['columns'], $key['foreignTable'], $key['foreignColumns'], $key['onDelete']);
            }

            $schema->addTable($table);
        }

        return $schema;
    }

    protected function quoteDefault(Column $column): string
    {
        if ($column->type === 'boolean') {
            return $column->default === '1' ? 'true' : 'false';
        }

        return parent::quoteDefault($column);
    }

    protected function getChangeColumnSql(string $table, Column $from, Column $to): array
    {
        $prefix = 'ALTER TABLE ' . $this->quoteIdentifier($table) . ' ALTER ' . $this->quoteIdentifier($to->name) . ' ';
        $sql = [];

        if ($from->autoincrement && !$to->autoincrement) {
            $sql[] = $prefix . 'DROP IDENTITY IF EXISTS';
        }

        if (!$this->typesEqual($to->type, $from->type) || $from->length !== $to->length || $from->precision !== $to->precision || $from->scale !== $to->scale) {
            $type = $this->getTypeDeclaration($to);
            $sql[] = $prefix . 'TYPE ' . $type . ($to->type !== $from->type ? ' USING ' . $this->quoteIdentifier($to->name) . '::' . $type : '');
        }

        if ($from->default !== $to->default && !$to->autoincrement) {
            $sql[] = $prefix . ($to->default === null ? 'DROP DEFAULT' : 'SET' . $this->getDefaultDeclaration($to));
        }

        if ($from->nullable !== $to->nullable) {
            $sql[] = $prefix . ($to->nullable ? 'DROP NOT NULL' : 'SET NOT NULL');
        }

        if (!$from->autoincrement && $to->autoincrement) {
            $sql[] = $prefix . 'ADD GENERATED BY DEFAULT AS IDENTITY';
        }

        return $sql;
    }
}