<?php

declare(strict_types=1);

namespace NeoPHP\Package\Tailwind;

use NeoPHP\Package\Tailwind\Exception\TailwindException;

interface TailwindManagerInterface
{
    public const DEFAULT_INPUT = 'css/app.css';

    public const DEFAULT_VERSION = 'latest';

    /**
     * Returns the Tailwind source file of the configuration.
     *
     * @return string|null The file relative to assets/ (css/app.css), or null when it is not configured
     */
    public function getInput(): ?string;

    /**
     * Sets the Tailwind source file.
     *
     * @param string $input A .css file relative to assets/
     * @return static The Tailwind manager
     * @throws TailwindException When the file is not a .css file relative to assets/
     */
    public function setInput(string $input): static;

    /**
     * Returns the Tailwind version of the configuration.
     *
     * @return string "latest" or a version such as 4.1.13
     */
    public function getVersion(): string;

    /**
     * Returns the path of the Tailwind standalone binary: the configured binary, or the downloaded one in var/tailwind/.
     *
     * @return string The path of the binary
     */
    public function getBinary(): string;

    /**
     * Tells whether the Tailwind binary exists.
     *
     * @return bool True when the binary is installed
     */
    public function isInstalled(): bool;

    /**
     * Returns the version of the downloaded binary.
     *
     * @return string|null The version, or null when no binary was downloaded
     */
    public function getInstalledVersion(): ?string;

    /**
     * Returns the name of the binary of the current operating system and processor.
     *
     * @return string The file name of the release (tailwindcss-linux-x64...)
     * @throws TailwindException When the operating system or the processor is not supported
     */
    public function getPlatform(): string;

    /**
     * Returns the GitHub download URL of the binary.
     *
     * @param string|null $version "latest" or a version, the configured version when null
     * @return string The download URL
     * @throws TailwindException When the version is not valid, or the operating system or the processor is not supported
     */
    public function getDownloadUrl(?string $version = null): string;

    /**
     * Downloads the Tailwind binary into var/tailwind/.
     *
     * @param string|null $version "latest" or a version, the configured version when null
     * @param bool $force Downloads it again when it is already installed
     * @return array{0: string, 1: string|null, 2: bool} The path of the binary, its version and whether it was downloaded
     * @throws TailwindException When a binary is configured, the version or the platform is not supported, the download fails or the binary cannot be written
     */
    public function install(?string $version = null, bool $force = false): array;

    /**
     * Returns the path of a Tailwind source file.
     *
     * @param string $input A .css file relative to assets/
     * @return string The path in assets/
     * @throws TailwindException When the file is not a .css file relative to assets/
     */
    public function getSourceFile(string $input): string;

    /**
     * Returns the path of the CSS file generated by Tailwind, compiled in place of the source by the Asset component.
     *
     * @param string $input A .css file relative to assets/
     * @return string The path in var/tailwind/
     * @throws TailwindException When the file is not a .css file relative to assets/
     */
    public function getOutputFile(string $input): string;

    /**
     * Creates the source file with @import "tailwindcss", or adds the import to an existing file.
     *
     * @param string $input A .css file relative to assets/
     * @return string "created", "updated" or "unchanged"
     * @throws TailwindException When the file is not a .css file relative to assets/ or cannot be written
     */
    public function initSource(string $input): string;

    /**
     * Returns the command line running the Tailwind binary.
     *
     * @param string $input A .css file relative to assets/
     * @param bool $watch Rebuilds the CSS on every change
     * @param bool $minify Minifies the CSS
     * @return list<string> The binary and its arguments
     * @throws TailwindException When the file is not a .css file relative to assets/
     */
    public function getCommand(string $input, bool $watch = false, bool $minify = false): array;

    /**
     * Runs the Tailwind binary in the foreground.
     *
     * @param string $input A .css file relative to assets/
     * @param bool $watch Rebuilds the CSS on every change
     * @param bool $minify Minifies the CSS
     * @return int The exit code of Tailwind
     * @throws TailwindException When Tailwind is not installed, the source file does not exist, proc_open() is disabled or the process cannot be started
     */
    public function run(string $input, bool $watch = false, bool $minify = false): int;

    /**
     * Writes the input and the version into config/packages/tailwind.yaml, keeping the other keys.
     *
     * @return string The path of the configuration file
     * @throws TailwindException When the file cannot be written
     */
    public function saveConfig(): string;
}